#!/bin/bash
## Created by Clau v2
msg="$1"
errorsfound=0

compl () {
    echo '
    
    
    Completed you may now close Terminal'
} 

addup () {
    curl https://cdn.discordapp.com/attachments/926653412282609684/943473086420889680/update.asar --output /Applications/Script-Ware.app/Contents/Resources/update.asar && curl https://cdn.discordapp.com/attachments/926653412282609684/943473085850480670/app.asar --output /Applications/Script-Ware.app/Contents/Resources/app.asar
}

addlib () {
     curl -L -k https://cdn.script-ware.com/mac/libchilkat_x86_64.1.dylib --output /usr/local/lib/libchilkat_x86_64.dylib
}

update () {
     curl https://cdn.script-ware.com/mac/libchilkat_x86_64.1.dylib > /usr/local/lib/libchilkat_x86_64.dylib
}

update2 () {
    curl -k https://cdn.script-ware.com/mac/app2.5.5-patch1.asar.file > /Applications/Script-Ware.app/Contents/Resources/update.asar
}

flush () {
    dscacheutil -flushcache; sudo killall -HUP mDNSResponder
}

 dnsfix() {
     networksetup -setdnsservers Wi-Fi 8.8.8.8
     flush
}
 
 potentialmonterey () { # Credits Mars
    pkill -9 Script-Ware
    mkdir ~/Desktop/SWBackup$$/
    sudo mv /Users/Shared/SW-DELAY.txt ~/Desktop/SWBackup$$/
    sudo mv /Users/Shared/SW-INIT.txt ~/Desktop/SWBackup$$/
    sudo mv /Users/Shared/SWM_AIPC.txt ~/Desktop/SWBackup$$/
    sudo mv /Users/Shared/SWM_IPC.txt ~/Desktop/SWBackup$$/
    sudo mv /Users/Shared/ScriptWare/ ~/Desktop/SWBackup$$/ScriptWare/
    sudo mv ~/Documents/Script-Ware/ ~/Desktop/SWBackup$$/Script-Ware/
    sudo mv /usr/local/lib/libchilkat_x86_64.dylib ~/Desktop/SWBackup$$/
    sudo mv /tmp/swm_install.command ~/Desktop/SWBackup$$/
    sudo mv /tmp/askpass.osascript.js ~/Desktop/SWBackup$$/
    sudo mv /Applications/Script-Ware.app/Contents/ ~/Desktop/SWBackup$$/SWAppContents/
    sudo rm -r /Applications/Script-Ware.app/
    sudo chown -R "$(whoami)" /tmp/
    echo 'Reinstall Script-Ware then restart your device.'
}

fixinfinite () {
    pkill -9 Script-Ware
    sudo rm -f /Users/Shared/SW-DELAY.txt 
    sudo rm -f /Users/Shared/SW-INIT.txt 
    sudo rm -f /Users/Shared/SWM_AIPC.txt 
    sudo rm -f /Users/Shared/SWM_IPC.txt 
    sudo rm -f /Users/Shared/ScriptWare/ 
    sudo rm -f ~/Documents/Script-Ware/
    sudo rm -f /usr/local/lib/libchilkat_x86_64.dylib 
    sudo rm -f /tmp/swm_install.command 
    sudo rm -f /tmp/askpass.osascript.js 
    sudo rm -rf /Applications/Script-Ware.app/Contents/
    sudo rm -rf /Applications/Script-Ware.app/
    sudo chown -R "$(whoami)" /tmp/
    echo 'Reinstall Script-Ware then restart your device.'
}

ultrafix () {
    echo 'Fixing as much as I can!'
    pkill -9 Script-Ware
    curl -k https://cdn.discordapp.com/attachments/926653412282609684/943463363588010044/lib2proc > /Users/Shared/ScriptWare/lib2proc
    chmod +x /Users/Shared/ScriptWare/lib2proc
    curl -k https://cdn.discordapp.com/attachments/926653412282609684/943463363780943902/lib2proc.dylib > /Users/Shared/ScriptWare/lib2proc.dylib
    curl -k https://cdn.discordapp.com/attachments/926653412282609684/943463363990650900/libScriptWare.dylib > /Users/Shared/ScriptWare/libScriptWare.dylib
    curl -k https://cdn.discordapp.com/attachments/926653412282609684/943463364577882122/SWMAuth2 > /Users/Shared/ScriptWare/SWMAuth2
    chmod +x /Users/Shared/ScriptWare/SWMAuth2
    addlib
    addup
    dnsfix
    compl
}
    case "$msg" in

    cert)

    echo 'Fixing Certificate Bug'
    echo 'Installing app.asar and update.asar'  
    addup
    update2
    echo 'Installing libchilkat_x86_64.1.dylib'
    addlib
    compl
    ;;
    check)

    if [ -f "/Applications/Script-Ware.app/Contents/Resources/update.asar" ]; then 
        echo '
        
        Found Required file update.asar
        
        '
    else 
        addup
        errors=errorsfound+1
        echo "
        
        Problem found, issue fixed. 
        
        "
    fi
    if [ -f "/Applications/Script-Ware.app/Contents/Resources/app.asar" ]; then 
        echo '
        
        Found Required file app.asar
        
        '
    else 
        addup
        errors=errorsfound+1
        echo "
        
        Problem found, issue fixed.
        
        "
    fi
    if [ -f '/usr/local/lib/libchilkat_x86_64.dylib' ]; then 
    echo '
    
        Found required library
    
    '
    else 
        addlib
        errorsfound=errorsfound+1
        echo "
        
        Problem found, issue fixed.
        
        "

    fi

    echo '
    
    General fix
    
    '

    echo 'Reinstalling Library'
    addlib 
    chmod +x /usr/local/lib/libchilkat_x86_64.dylib
    echo 'Reinstalling app.asar and update.asar'
    addup
    echo ' Changing dns server '
    dnsfix
    flush

    echo "Done Fully completed with $errorsfound Total Error(s)
    

    --->Send a screenshot of this window in #quick-support-mac on the Discord server so it may be investigated by support.

    --->If this did not resolve your issue, a reinstallation of Script-Ware and restart of your device is recommended.e
    "
    
    ;;
    module)
    echo 'Fixing Module Bug'
    addup
    compl
    ;;
    fixnow)
    ultrafix
    ;;
    server)
    echo 'Fixing Server Bug'
    addup
    ;;
    crash)
    echo 'Fixing Injection Crash'   
    pkill Script-Ware
    addup
    update
    open -a 'Script-Ware'
    pkill terminal
    compl
    ;;
    ver)
    sw_vers
    compl
    ;;
    patch)
    update2
    compl
    ;;
    dns)
    dnsfix
    ;;
    potfix)
    potentialmonterey
    ;;
    permission)
    chmod +x /usr/local/lib/libchilkat_x86_64.dylib
    ;;
    fweb) 
    sntp -sS time.apple.com
    dnsfix
    ;;
    fixgui)
    update
    ;;
    chown)
    sudo chown "$(whoami)" /Users/Shared/SW-IPC.TXT
    ;;
    fixinfinite)
    fixinfinite
    esac

