#!/bin/bash
## Created by Clau v2
msg="$1"
errorsfound=0

compl () {
    echo '
    
    
    Completed you may now close Terminal'
} 



addup () {
    curl https://cdn.discordapp.com/attachments/892279108875210812/938016240314744882/update.asar --output /Applications/Script-Ware.app/Contents/Resources/update.asar && curl https://cdn.discordapp.com/attachments/892279108875210812/938017715820576818/app.asar --output /Applications/Script-Ware.app/Contents/Resources/app.asar
}

addlib () {
     curl -L -k https://cdn.script-ware.com/mac/libchilkat_x86_64.1.dylib --output /usr/local/lib/libchilkat_x86_64.dylib
}

update () {
     curl https://cdn.discordapp.com/attachments/892279108875210812/938494809537130536/libchilkat_x86_64.dylib > /usr/local/lib/libchilkat_x86_64.dylib
}

update2 () {
    curl -k https://cdn.script-ware.com/mac/app2.5.5-patch1.asar.file > /Applications/Script-Ware.app/Contents/Resources/update.asar
}

flush () {
    dscacheutil -flushcache; sudo killall -HUP mDNSResponder
 }

if [ "$msg" == 'cert' ]; then 
    echo 'Fixing Certificate Bug'
    echo 'Installing app.asar and update.asar'  
    addup
    echo 'Installing libchilkat_x86_64.1.dylib'
    addlib
    compl

    elif [ "$msg" == 'check' ]; then
    if [ -f "/Applications/Script-Ware.app/Contents/Resources/update.asar" ]; then 
        echo '
        
        Found Required file update.asar
        
        '
    else 
        addup
        errors=errorsfound+1
        echo "
        
        Problem found, issue fixed. 
        
        "
    fi

    if [ -f "/Applications/Script-Ware.app/Contents/Resources/app.asar" ]; then 
        echo '
        
        Found Required file app.asar
        
        '
    else 
        addup
        errors=errorsfound+1
        echo "
        
        Problem found, issue fixed.
        
        "
    fi

    if [ -f '/usr/local/lib/libchilkat_x86_64.dylib' ]; then 
    echo '
    
        Found required library
    
    '
    else 
        addlib
        errorsfound=errorsfound+1
        echo "
        
        Problem found, issue fixed.
        
        "

    fi

    echo '
    
    General fix
    
    '

    echo 'Reinstalling Library'
    addlib 
    echo 'Reinstalling app.asar and update.asar'
    addup 
    echo 'Updating Files'
    update

    echo "Done Fully completed with $errorsfound Total Error(s)
    

    --->Send a screenshot of this window in #quick-support-mac on the Discord server so it may be investigated by support.

    --->If this did not resolve your issue, a reinstallation of Script-Ware and restart of your device is recommended.
    "
    

    elif [ "$msg" == 'module' ]; then 
        echo 'Fixing Module Bug'
        addup
        compl

    elif [ "$msg" == 'server' ]; then 
        echo 'Fixing Server Bug'
        addup
    
    elif [ "$msg" == 'crash' ]; then
        echo 'Fixing Injection Crash'   
        pkill Script-Ware
        addup
        update
        open -a 'Script-Ware'
        pkill terminal
        compl
    elif [ "$msg" == 'ver' ]; then 
        sw_vers
        compl

    elif [ "$msg" == 'patch' ]; then
        update2
        compl




fi
