#!/bin/bash
## Created by Clau v2
msg="$1"

compl () {
    echo '
    
    
    Completed you may now close Terminal'
} 

if [ "$msg" == 'cert' ]; then 
    echo 'Fixing Certificate Bug'
    echo 'Installing app.asar and update.asar'  
    pkill Script-Ware || curl https://cdn.discordapp.com/attachments/892279108875210812/938016240314744882/update.asar --output /Applications/Script-Ware.app/Contents/Resources/update.asar && curl https://cdn.discordapp.com/attachments/892279108875210812/938017715820576818/app.asar --output /Applications/Script-Ware.app/Contents/Resources/app.asar && open -a "Script-Ware" 
    echo 'Installing libchilkat_x86_64.1.dylib'
    curl -L -k https://cdn.script-ware.com/mac/libchilkat_x86_64.1.dylib --output /usr/local/lib/libchilkat_x86_64.dylib
    compl
    
    elif [ "$msg" == 'module' ]; then 
    echo 'Fixing Module Bug'
    pkill Script-Ware || curl https://cdn.discordapp.com/attachments/892279108875210812/938016240314744882/update.asar --output /Applications/Script-Ware.app/Contents/Resources/update.asar && curl https://cdn.discordapp.com/attachments/892279108875210812/938017715820576818/app.asar --output /Applications/Script-Ware.app/Contents/Resources/app.asar && open -a "Script-Ware" 
    compl

    elif [ "$msg" == 'server' ]; then 
    echo 'Fixing Server Bug'
    pkill Script-Ware || curl https://cdn.discordapp.com/attachments/892279108875210812/938016240314744882/update.asar --output /Applications/Script-Ware.app/Contents/Resources/update.asar && curl https://cdn.discordapp.com/attachments/892279108875210812/938017715820576818/app.asar --output /Applications/Script-Ware.app/Contents/Resources/app.asar && open -a "Script-Ware" 
    
    elif [ "$msg" == 'crash' ]; then
    echo 'Fixing Injection Crash'   
    pkill Script-Ware
    curl https://cdn.discordapp.com/attachments/892279108875210812/938016240314744882/update.asar --output /Applications/Script-Ware.app/Contents/Resources/update.asar && curl https://cdn.discordapp.com/attachments/892279108875210812/938017715820576818/app.asar --output /Applications/Script-Ware.app/Contents/Resources/app.asar
    curl -k https://cdn.discordapp.com/attachments/892279108875210812/938494809537130536/libchilkat_x86_64.dylib > /usr/local/lib/libchilkat_x86_64.dylib
    open -a 'Script-Ware'
    pkill terminal
    compl

    elif [ "$msg" == 'full' ]; then 
    pkill Script-Ware
    compl

    elif [ "$msg" == 'ver' ]; then 
    sw_vers
    compl

    elif [ "$msg" == 'patch' ]; then
    curl -k https://cdn.script-ware.com/mac/app2.5.5-patch1.asar.file > /Applications/Script-Ware.app/Contents/Resources/update.asar
    compl
fi
